// src/components/SecretList.tsx
import { Component, For } from "solid-js";
import type { SecretListEntry } from "@aws-sdk/client-secrets-manager";
import styles from "./SecretList.module.css";
import SecretListItem from "./SecretListItem";

interface Props {
    secrets: SecretListEntry[];
}

export default function SecretList({ secrets }: Props) {
    if (secrets.length < 1) {
        return <div class={styles.empty}>No secrets found.</div>;
    }

    return (
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Last Changed</th>
                </tr>
            </thead>
            <tbody>
                <For each={secrets}>
                    {(secret, i) => <SecretListItem secret={secret} />}
                </For>
            </tbody>
        </table>
    );
}

// src/lib/components/SecretList.svelte
<script lang="ts">
    import type { SecretListEntry } from "@aws-sdk/client-secrets-manager";
    import SecretListItem from "./SecretListItem.svelte";

    interface Props {
        secrets: SecretListEntry[];
    }

    const { secrets }: Props = $props();
</script>

{#if secrets.length === 0}
    <div class="empty">No secrets found.</div>
{:else}
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Last Changed</th>
                <th>Rotation</th>
            </tr>
        </thead>

        <tbody>
            {#each secrets as secret, i (secret.ARN ?? i)}
                <SecretListItem {secret} />
            {/each}
        </tbody>
    </table>
{/if}
